[ORCT-197] amend eslint misuse
AliceO2Group/RunConditionTable pull request #246
Opened 2023-10-17 09:52 UTC by xsalonx

#### I have a JIRA ticket
- [x] branch and/or PR name(s) include(s) JIRA ID
- [ ] issue has "Fix version" assigned
- [x] issue "Status" is set to "In review"
- [x] PR labels are selected

Notable changes for users:
- NA

Notable changes for developers:
- by accident, directory `lib/database` was provided inside exclude clause of eslint configuration, what resulted in many hidden, styling errors

Changes made to the database:
- NA

2023-10-17 12:39 UTC, martinboulais requested changes

2023-10-17 12:41 UTC, xsalonx commented on app/lib/database/utilities/PGQueryBuilder.js
> +            .filter(([k, _]) => k.match(filterTypesRegex))
indeed

2023-10-17 12:42 UTC, xsalonx commented on app/lib/database/views/flags_view.js
> +        .filter((_) => _)
right

2023-10-17 12:48 UTC, xsalonx commented on app/lib/database/views/flags_view.js
> +        .filter((_) => _)
refactored

2023-10-17 12:48 UTC, xsalonx commented on app/lib/database/utilities/PGQueryBuilder.js
> +            .filter(([k, _]) => k.match(filterTypesRegex))
refactored

2023-10-18 12:21 UTC, martinboulais approved these changes

2023-10-18 12:28 UTC, merged